### ISSUE TITLE
[BUG]: Issue with indent-blankline Plugin

### ISSUE THREAD

**Issue by kelphil** [2KAbhishek/nvim2k#11]
### Description of the bug

Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:30: Error executing lua: /usr/share/nvim/runtime/filetype.lua:31: BufReadPost Autocommands for "*"..FileType Autocommands for "lua"..FileType Autocommands for "*": Vim(a
ppend):Error executing lua callback: ...l/share/nvim/lazy/indent-blankline.nvim/lua/ibl/init.lua:478: invalid key: virt_text_repeat_linebreak

![image](https://github.com/2KAbhishek/nvim2k/assets/16230838/34d59321-f828-4ba2-a2bb-1fc86871ef50)

### Steps To Reproduce

1. git clone nvim2k repo
2. open nvim

### Additional Information

Environment: Ubuntu 20.04 LTS via WSL on Windows 11 Pro 

_No response_

**Comment by 2KAbhishek** [comment]
Thanks a lot for reporting, can you please share your neovim version

Let's work together to resolve this

**Comment by 2KAbhishek** [comment]
@kelphil can you please let me know if you are still facing the issue and share more details on this

**Comment by kelphil** [comment]
Hi @2KAbhishek,

Thanks for offering to look into this issue. I am using nvim v0.10.0-dev version

![image](https://github.com/2KAbhishek/nvim2k/assets/16230838/5abc4750-17c7-4d4d-94e5-bdeaf5cb7268)

**Comment by 2KAbhishek** [comment]
Can you try deleting `~/.local/share/nvim/lazy/indent-blankline.nvim` and opening nvim agian.

Also helpful to try Lazy clean and Lazy update

**Comment by kelphil** [comment]
I tried your suggestion above to deleting ~/.local/share/nvim/lazy/indent-blankline.nvim and opening nvim agian. I saw the indent-blankline plugin was successfully installed by Lazy.

However, I am still getting these errors while opening plugins/list.lua file 

![image](https://github.com/2KAbhishek/nvim2k/assets/16230838/d547a789-3dbf-49fb-8560-361b5191389f)
![image](https://github.com/2KAbhishek/nvim2k/assets/16230838/ea331bf5-4440-4442-9e36-c817350dfa2a)

Once I got past the above by hitting ENTER; I get these errors while scrolling down in the file using DOWN ARROW key:
![image](https://github.com/2KAbhishek/nvim2k/assets/16230838/0f7914fd-769b-419c-b42f-4d44eef98ecc)

Closing and reopening the file shows this error:
![image](https://github.com/2KAbhishek/nvim2k/assets/16230838/9939e607-868e-4ce9-8b70-d6f03993cf68)

**Comment by 2KAbhishek** [comment]
Now the issue seems to be coming from dashboard :/

I am not sure what's going on, can you try commenting out the `lua/core/autocmd.lua` file contents

Also try :TSUpdate after opening a lua file once
