### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by deliri** [2KAbhishek/nvim2k#21]
### Description

Hello Abishek,

I hope this message finds you well. I've been thoroughly enjoying using your Neovim setup, which I find impeccably designed and highly efficient for my development workflow. The attention to detail and the quality of the configuration is admirable, and it has significantly improved my coding experience.

However, I've noticed that the current setup doesn't include support for the Go programming language. As a Go developer, integrating Go support would greatly enhance the utility and completeness of this Neovim configuration for myself and other Go developers.

I came across an implementation in another repository that seems to work well and could potentially serve as a good reference for integrating Go support into your setup. Here’s the link to the specific configuration: [nvim-golang-setup](https://github.com/adibhanna/nvim/blob/main/lua/plugins/golang.lua). This example includes features such as autocompletion, diagnostics, and formatting, which I believe would complement your setup nicely.

Would it be possible to consider adding Go language support to the Neovim configuration? I believe that this addition would make the setup even more comprehensive and beneficial for a wider range of users.

Thank you very much for considering this request. I am looking forward to any possibility of this enhancement and am more than willing to assist in testing or providing further information if needed.

Warm regards,

**Comment by 2KAbhishek** [comment]
Hey @deliri thanks for opening up the issue and the kind words!

For go I believe adding the required LSP, Treesitter and Mason packages should do the trick.

I will be adding an option to enable language support in an upcoming PR.

**Comment by 2KAbhishek** [comment]
@deliri this should now be addressed, if you have go present in your path, the lsp server will be automatically installed, null ls and treesitter are present for go by default
