### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by mnrvr** [2KAbhishek/nvim2k#5]
### Description of the bug

Minor bug .. there was a change FROM 'help' TO 'vimdoc' in treesitter lua language

fix was: lua/nvim2k/treesitter.lua line 7
 `ensure_installed = { 'vimdoc', 'lua', 'markdown' },`

in my install

### Steps To Reproduce

Recent MacOS install.

**Comment by 2KAbhishek** [comment]
fixed in https://github.com/2KAbhishek/nvim2k/commit/f2f0394b3a199645f7a6b2daad9e58b8d3cb973e, thanks @mnrvr
