### ISSUE TITLE
[BUG]:  Run UpdateRemotePlugins during Wilder initialization

### ISSUE THREAD

**Issue by doctorfree** [2KAbhishek/nvim2k#6]
### Description of the bug

The `wilder.nvim` plugin complains about missing functions

### Steps To Reproduce

Initialize configuration with  `nvim --headless "+Lazy! sync" +qa`

### Additional Information

Initialize the Wilder plugin with something like:

```lua
build = function()
        vim.cmd([[silent UpdateRemotePlugins]])
end
```

**Comment by 2KAbhishek** [comment]
Thanks for the suggestion, I have integrated the change!
