### ISSUE TITLE
Add personalization features

### ISSUE THREAD

**Issue by HexSleeves** [2KAbhishek/nvim2k#9]
Hello! Wanted to say I really love this setup. I have been messing with it making my own, but as I was making my own an idea crossed my head. What if you added configuration options to allow for a customized user setup to me merged with the core setup? 

That way any user could clone this repo and still be able to get updates you make to the core repo, but their user folder will act as  an override allowing them to override some default.

This is something along how other distros do it: I.e. lazy and Astro, and Chad

If this is no interest to you, I understand, just though I would float the idea! Would love to collaborate if possible

**Comment by 2KAbhishek** [comment]
That sounds really interesting, can you please tell me more

What directory structure and overriding function did you have in mind?

**Comment by HexSleeves** [comment]
Sorry for the late response I was traveling all day for vacation trip!

So what I was thinking was some system that allows for customizations, but also allows to still receive updates from the core you have created.

A quick thought of how the system could work would be either a `custom` folder or `user` folder where they are able to define keymaps, options, autocmds, etc which will be merged back into the main config before relaying that back to either `lazy.nvim` or `nvim` itself.

Two ways to approach it: 

You could make a library who's entire purpose is to be consumed by `lazy.nvim` and it hides most of the internals. Imagine taking the repo you created and basically making it a `nvim` plugin which is consumed and then built upon


The other is simplier in the sense where the repo is to be cloned by each individual, and they create their custom folder to insert their modifications with.
|-> core (core)
|-> libs (core)
|-> plugins (core)
|-> custom (user)
--|-> init.lua (could be used to define a table to be consumed by main config or have specific file names be consumed like below)
--|-> keymaps.lua (merge with main keymaps; theirs takes precedence) 
--|-> plugins.lua ((merge with main plugins; theirs takes precedence; they can tweak ops or completely override a plugin)
--|-> cmds.lua (merge with main autcmds / cmds; theirs takes precedence)

**Comment by 2KAbhishek** [comment]
This gives me an idea of setting up a user module, will share details when I get some time to work on it

**Comment by 2KAbhishek** [comment]
Addressed this on #10 @lecoqjacob why don't you take a look
